"""add generation weather and forecast tables

Revision ID: 9baf4d80ea13
Revises: 4bd922d4c291
Create Date: 2026-09-12 11:24:04.472206
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by atexit.
revision = '9baf4d80ea13'
down_revision = '4bd922d4c291'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('forecast_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('p10_mw', sa.Float(), nullable=False),
    sa.Column('p50_mw', sa.Float(), nullable=False),
    sa.Column('p90_mw', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasts_forecast_timestamp'), 'forecasts', ['forecast_timestamp'], unique=False)
    op.create_index(op.f('ix_forecasts_id'), 'forecasts', ['id'], unique=False)
    op.create_index(op.f('ix_forecasts_plant_id'), 'forecasts', ['plant_id'], unique=False)
    op.create_index('ix_forecasts_plant_id_forecast_timestamp', 'forecasts', ['plant_id', 'forecast_timestamp'], unique=False)
    op.create_table('historical_generation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generation_mw', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_generation_id'), 'historical_generation', ['id'], unique=False)
    op.create_index(op.f('ix_historical_generation_plant_id'), 'historical_generation', ['plant_id'], unique=False)
    op.create_index('ix_historical_generation_plant_id_timestamp', 'historical_generation', ['plant_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_historical_generation_timestamp'), 'historical_generation', ['timestamp'], unique=False)
    op.create_table('weather_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('humidity_percent', sa.Float(), nullable=False),
    sa.Column('wind_speed_mps', sa.Float(), nullable=False),
    sa.Column('wind_direction_deg', sa.Float(), nullable=False),
    sa.Column('cloud_cover_percent', sa.Float(), nullable=False),
    sa.Column('precipitation_mm', sa.Float(), nullable=False),
    sa.Column('radiation_w_m2', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_data_id'), 'weather_data', ['id'], unique=False)
    op.create_index(op.f('ix_weather_data_plant_id'), 'weather_data', ['plant_id'], unique=False)
    op.create_index('ix_weather_data_plant_id_timestamp', 'weather_data', ['plant_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_weather_data_timestamp'), 'weather_data', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_data_timestamp'), table_name='weather_data')
    op.drop_index('ix_weather_data_plant_id_timestamp', table_name='weather_data')
    op.drop_index(op.f('ix_weather_data_plant_id'), table_name='weather_data')
    op.drop_index(op.f('ix_weather_data_id'), table_name='weather_data')
    op.drop_table('weather_data')
    op.drop_index(op.f('ix_historical_generation_timestamp'), table_name='historical_generation')
    op.drop_index('ix_historical_generation_plant_id_timestamp', table_name='historical_generation')
    op.drop_index(op.f('ix_historical_generation_plant_id'), table_name='historical_generation')
    op.drop_index(op.f('ix_historical_generation_id'), table_name='historical_generation')
    op.drop_table('historical_generation')
    op.drop_index('ix_forecasts_plant_id_forecast_timestamp', table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_plant_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_forecast_timestamp'), table_name='forecasts')
    op.drop_table('forecasts')
    # ### end Alembic commands ###
